### ISSUE TITLE
Having a default value for deep_get

### ISSUE THREAD

**Issue by Cediddi** [mbello/dict-deep#1]
I think deep_get() should have a default value option or a similar way to ignore missing values, just like in the dict.get(). For dict, `key in dict` check is a simple alternative to get but for nested dicts, there's no way to check if the key exists at all.

**Comment by tschaume** [comment]
I think the `accessor` argument has taken over for default since version 3. See [usage](https://github.com/mbello/dict-deep/blob/master/README.md#usage)

**Comment by mbello** [comment]
It is true that since version 3, the accessor became a necessity to support a default.

I just released version 4 with many fixed and many improvements, basically making the code shorter, faster, more robust and with better defaults for those that will use the code with dicts. But I had to bump the major version because I introduced changes that can break existing code.

With this new version there is no need to pass an accessor or getter most of the time if you are working with dicts. This is true for all methods. Despite these better defaults, the code still works perfectly fine if the structure is built with some other type/model.

deep_get now takes an additional optional getter_last_step parameter (see README). 

deep_del now has a getter parameter and was completely rewritten, fixing bugs. The return value changed, now deep_del only returns the number of itens deleted, it no longer returns a tuple with the values deleted.

So please take a look at version 4 and use it.

Thanks for the feedback, if you have suggestions I am all ears.

**Comment by Cediddi** [comment]
Cool! I'll look into the new version

**Comment by mbello** [comment]
@Cediddi Let me know if this version works fine for you.
